package initwizard

import (
	"context"
	"fmt"
	"os"

	"github.com/driftee-ai/drift/pkg/config"
	"github.com/driftee-ai/drift/pkg/llm"
	"gopkg.in/yaml.v3"
)

func RunWizard(dir string, fastMode bool, nonInteractive bool, providerArg string) error {
	var finalRules []config.Rule
	var provider string
	var usage llm.Usage

	if nonInteractive {
		provider = providerArg // Use the provider specified by the argument
		fmt.Printf("Running in non-interactive mode. Analyzing repository at '%s'...\n", dir)

		files, err := ScanProject(dir, fastMode)
		if err != nil {
			return fmt.Errorf("scan failed: %w", err)
		}

		client, err := llm.New(provider)
		if err != nil {
			return fmt.Errorf("failed to initialize LLM client: %w", err)
		}

		fmt.Printf("Found %d relevant files. Asking %s LLM to generate rules...\n", len(files), provider)
		mapper := NewMapper(client)
		rules, runUsage, err := mapper.MapFiles(context.Background(), files, fastMode)
		if err != nil {
			return fmt.Errorf("failed to generate mapping rules: %w", err)
		}

		if len(rules) == 0 {
			fmt.Println("No rules generated by the LLM.")
			return nil
		}

		finalRules = rules
		usage = runUsage
	} else {
		// Run interactive TUI
		rules, runUsage, selProvider, err := runReviewApp(dir, fastMode)
		if err != nil {
			return err
		}
		if len(rules) == 0 || selProvider == "" {
			fmt.Println("Initialization cancelled. No configuration generated.")
			return nil
		}
		finalRules = rules
		usage = runUsage
		provider = selProvider
	}

	// Step 2: Save Config
	cfg := config.Config{
		Version:  1,
		Provider: provider,
		Rules:    finalRules,
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}

	commentedData := []byte("# .drift.yaml\n# This file defines the rules for checking drift between your code and documentation.\n\n" + string(data))
	if err := os.WriteFile(".drift.yaml", commentedData, 0644); err != nil {
		return fmt.Errorf("failed to write .drift.yaml: %w", err)
	}

	fmt.Println("\n✨ Success! Generated .drift.yaml configuration.")
	if usage.TotalTokens > 0 {
		fmt.Printf("📊 Built %d rules using %d LLM tokens.\n", len(finalRules), usage.TotalTokens)
	} else {
		fmt.Printf("📊 Built %d rules.\n", len(finalRules))
	}
	fmt.Println("🚀 You can now run 'drift check' to ensure your documentation is up to date.")
	return nil
}
