package llm

import "context"

// Usage tracks the number of tokens processed and generated by the LLM.
type Usage struct {
	PromptTokens     int
	CompletionTokens int
	TotalTokens      int
}

// Client is a generic interface for interacting with Large Language Models.
type Client interface {
	// GenerateJSON sends a prompt to the LLM and attempts to return the output formatted
	// according to either a generic JSON Schema passed via interface{} or via prompt instructions.
	GenerateJSON(ctx context.Context, prompt string, schema interface{}) (string, Usage, error)
}

// DummyClient is a mock client for testing purposes.
type DummyClient struct{}

// NewDummyClient creates a new DummyClient.
func NewDummyClient() *DummyClient {
	return &DummyClient{}
}

// GenerateJSON returns a hardcoded assessment result.
func (c *DummyClient) GenerateJSON(ctx context.Context, prompt string, schema interface{}) (string, Usage, error) {
	return `{"is_in_sync": true, "reason": "This is a dummy assessment from the generic llm adapter."}`, Usage{}, nil
}
